# Generated by Django 4.1.1 on 2022-09-29 13:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ["F", "Feminino"],
                            ["M", "Masculino"],
                            ["N", "Nenhuma das opções"],
                        ],
                        max_length=1,
                    ),
                ),
            ],
            managers=[("objetos", django.db.models.manager.Manager()),],
        ),
        migrations.DeleteModel(name="Funcionario",),
    ]
