# Generated by Django 4.1.1 on 2022-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_usuario_delete_funcionario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("sobrenome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("tempo_de_servico", models.IntegerField(default=0)),
                ("remuneracao", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(name="Usuario",),
    ]
